version: '3.3'

volumes:
  plt-mysql-data:

services:
  db:
    image: mysql:latest
    volumes:
      - "plt-mysql-data:/var/lib/mysql"
    restart: always
    ports:
      - 37500:3306
    environment:
      MYSQL_DATABASE: "plt"
      MYSQL_USER: "beta"
      MYSQL_PASSWORD: "kawaikawai"
      MYSQL_ROOT_PASSWORD: "betaiskawaikawai"

  adminer:
    image: adminer:latest
    ports:
      - 37501:8080


  core:
    build: core
    ports:
      - 17354:8000