version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: plt-mysql
    volumes:
      - "./plt-mysql-data:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - 37500:3306
    environment:
      MYSQL_DATABASE: "plt"
      MYSQL_USER: "beta"
      MYSQL_PASSWORD: "kawai"
      MYSQL_ROOT_PASSWORD: "betaiskawai"

  adminer:
    image: adminer:latest
    container_name: plt-mysql-adminer
    ports:
      - 37501:8080

  web:
    build: .
    image: plt-django:0.1
    container_name: plt-django
    ports:
      - 17534:8000
