version: '3.3'

volumes:
  plt-mysql-data:

services:
  db:
    image: mysql:latest
    container_name: plt-mysql
    volumes:
      - "plt-mysql-data:/var/lib/mysql"
    restart: always
    ports:
      - 37500:3306
    environment:
      MYSQL_DATABASE: "plt"
      MYSQL_USER: "beta"
      MYSQL_PASSWORD: "kawaikawai"
      MYSQL_ROOT_PASSWORD: "betaiskawaikawai"

  adminer:
    image: adminer:latest
    container_name: plt-mysql-adminer
    ports:
      - 37501:8080

  ssti:
    build: ./app/env/ssti/
    container_name: plt-ssti
    volumes:
      - "./app/env/ssti/flag.txt:/app/flag.txt"
    ports:
      - 37511:8080

  web:
    build: .
    image: plt-django:0.1
    container_name: plt-django
    ports:
      - 17534:8000
